# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-02 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email_adress', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('street_address1', models.CharField(max_length=40)),
                ('street_address2', models.CharField(max_length=40)),
                ('county', models.CharField(max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('town_or_city', models.CharField(max_length=40)),
                ('comments', models.CharField(max_length=300)),
                ('Bedrooms_nr', models.CharField(max_length=20)),
                ('Bathrooms_nr', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
